version: 2.1

jobs:
    build:
        docker:
        - image: cimg/node:14.14
        steps:
        - checkout
        - restore_cache:
              keys:
              - nm-{{ checksum "package.json" }}
        - run:
              name: NPM Install
              command: npm install
        - save_cache:
              key: nm-{{ checksum "package.json" }}
              paths:
              - node_modules
        - run:
              name: NPM Build
              command: npm run build
        - persist_to_workspace:
              root: ./
              paths:
              - out
    deploy:
        docker:
        - image: cimg/aws:2025.01
        steps:
        - attach_workspace:
              at: ./
        - run:
              name: Upload to s3
              command: aws s3 sync ./out s3://$S3_BUCKET_NAME/ --delete --acl public-read
        - run:
              name: Invalidate Cloudfront Cache
              command: aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/*"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires: 
          - build
          filters:
            branches:
                  only: main
