version: 2.1

jobs:
    build:
        docker:
        - image: cimg/node:14.14
        steps:
        - checkout
        - restore_cache:
              keys:
              - nm-{{ checksum "package.json" }}
        - run:
              name: NPM Install
              command: npm install
        - save_cache:
              key: nm-{{ checksum "package.json" }}
              paths:
              - node_modules
        - run:
              name: NPM Build
              command: npm run build
        - persist_to_workspace:
              root: ./
              paths:
              - out

workflows:
    build-deploy:
    jobs:
        - build:
        filters:
            branches:
                only: main
